PP-5010 Added libraries for Java 11
- Container starts with following warnings but works fine and passes end to end tests
     java.lang.NoClassDefFoundError: javax/activation/DataSource
     java.lang.NoClassDefFoundError: javax/xml/bind/PropertyException
- Added dependecies that are missing for Jersey library for above warnings.