Added groovy library
- Pact version 3.6.3 requires latest `groovy` library. But, due to the library being a transitive dependency, an old version is being used and resulting into following error for pact tests
    java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/memoize/EvictableCache